package com.example.quiz5.Data;

import android.net.Uri;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

//Annotates that this entity to be stored in a database
// gives the tableName to be stored in to be "info_table"
@Entity(tableName = "info_table")
public class PhotoInfo {
    //Autogenerated id to be used as primary key in the database
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    private int Id;

    // Every photo will have a corresponding name
    // The name denotes what the
    @ColumnInfo(name = "name")
    private String name;

    // imageData is stored in the database as an array of bytes
    //The typeAffinity denotes that this column should store binary data
    @ColumnInfo(typeAffinity = ColumnInfo.BLOB)
    private byte[] imageData;

    //Constructor for the photoInfo object, takes in one String name and one byte array imageData
    public PhotoInfo(String name, byte[] imageData){
        this.name = name;
        this.imageData = imageData;
    }

    //Getters and setters

    public void setId(int newId){
        this.Id = newId;
    }
    public String getName(){
        return this.name;
    }

    public void setName(String newName){
        this.name = newName;
    }

    public byte[] getImageData(){
        return this.imageData;
    }

    public void setImageUri(byte[] newImageData){
        this.imageData = newImageData;
    }

    public int getId(){
        return this.Id;
    }
}
